// next/src/pages/index.tsx
import React from 'react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import got from 'got';

type User = { name: string; avatarUrl: string };

type ServerSideProps = {
  user: User;
};

export const getServerSideProps: GetServerSideProps<ServerSideProps> = async context => {
  // Simulate a request to an external server
  const userResponse = await got<User>('http://localhost:3000/api/users/me', {
    responseType: 'json',
  });
  const { body: user } = userResponse;

  return {
    props: {
      user,
    },
  };
};

export default function Index({ user }: ServerSideProps) {
  return (
    <>
      <Head>
        <title>SSR POC - Next</title>
      </Head>
      <div className="container">
        <img src={user.avatarUrl} alt="user-avatar" className="avatar" />
        <span>{user.name}</span>
      </div>
    </>
  );
}

// nuxt/src/pages/index.vue
<template>
  <div class="container">
    <img :src="user.avatarUrl" alt="user-avatar" class="avatar" />
    <span>{{ user.name }}</span>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

type User = { name: string; avatarUrl: string };

export default Vue.extend({
  head() {
    return {
      title: 'SSR POC - Nuxt',
    };
  },

  async asyncData({ $http }) {
    // Simulate a request to an external server
    const user: User = await $http.$get('http://localhost:3000/api/users/me');
    return { user };
  },
});
</script>

<style>
body {
  margin: 0;
}

.container {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  flex-direction: column;
}

.avatar {
  width: 150px;
  height: 150px;
  border-radius: 50%;
  margin-bottom: 8px;
}
</style>
